# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout support-system-database
      uses: actions/checkout@v2
      with:
        repository: januschung/support-system-db
        path: support-system-db

    - name: Bring up database
      run: docker-compose up -d
    
    - name: Checkout support-system-server
      uses: actions/checkout@v2
    
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15

    - name: Build with Maven
      run: mvn clean build
